server:
  port: 8008
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test
    username: sa
    password: 123456
  #    schema: classpath:db/schema.sql
    data: classpath:db/data.sql
  jpa:
    database: h2
    hibernate:
      ddl-auto: create
      format_sql: true
    show-sql: true
  h2:
    console:
      path: /h2-console
      enabled: true

logging:
  file:
    name: ship.log
  level:
    root: info
    com:
      diago:
        ship: debug
